# Generated by Django 3.1.2 on 2026-10-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201215_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userCommnet',
            new_name='userComment',
        ),
        migrations.AlterField(
            model_name='trivia',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
