services:
  dev:
    build:
      context: .
    container_name: trivia_dev
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/workspace
      - frontend_node_modules:/workspace/trivia_front/node_modules
    env_file:
      - .env

volumes:
  frontend_node_modules:
