"""
Django settings for drfapi project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Reads from DJANGO_SECRET_KEY (.env). The fallback below is only for local
# dev convenience and must be overridden with a real secret in production.
SECRET_KEY = os.environ.get(
  'DJANGO_SECRET_KEY', 'tiqo@)=ve0a6dwdey(urs_lgdnz(=l8hbkvbke#kc2xi7t8i9o'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get(
  'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,backend'
).split(',')


# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'api.apps.ApiConfig',
  'rest_framework',
  'rest_framework.authtoken',
  'corsheaders',
  'djoser',
  'django_filters',
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
  'corsheaders.middleware.CorsMiddleware',
]

# CORS_ORIGIN_WHITELIST = [
#     'http://10.84.36.83:8080',
#     'http://10.84.37.15:8080',
#     'http://192.168.3.12:8080',
# ]
# Defaults to allowing all origins for local dev convenience. Set
# DJANGO_CORS_ALLOW_ALL=False (and configure CORS_ORIGIN_WHITELIST above)
# for anything closer to production.
CORS_ORIGIN_ALLOW_ALL = os.environ.get('DJANGO_CORS_ALLOW_ALL', 'True') == 'True'

ROOT_URLCONF = 'drfapi.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'drfapi.wsgi.application'

REST_FRAMEWORK = {
  'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.IsAuthenticated',
  ],
  'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  ],
  'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

SIMPLE_JWT = {
  'AUTH_HEADER_TYPES': ('JWT',),
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# MySQL only (local dev uses the docker-compose "db" service by default;
# override DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD in .env to point at a
# real instance instead, e.g. production RDS).
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': os.environ.get('DB_NAME', 'haiku'),
    'USER': os.environ.get('DB_USER', 'haiku'),
    'PASSWORD': os.environ.get('DB_PASSWORD', 'haiku'),
    'HOST': os.environ.get('DB_HOST', 'db'),
    'PORT': os.environ.get('DB_PORT', '3306'),
  }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'api.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = Path.joinpath(BASE_DIR, 'media')
MEDIA_URL = '/media/'
